import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {toast} from 'sonner';
import AppLayout from '@/components/layout/AppLayout';
import {MateriaSelect} from '@/components/form/Selectors';
import {LoadingState,ErrorState,EmptyState} from '@/components/ui/states';
import {Coverage,getCoverage,studyPost} from '@/lib/study';
import {request} from '@/lib/api';
import {useMaterias} from '@/hooks/useConfiguracoes';

export default function CoveragePage({review=false}:{review?:boolean}){
 const [materia,setMateria]=useState('');const [filter,setFilter]=useState(review?'PENDÊNCIAS':'TODOS');
 const q=useQuery({queryKey:['estudos','cobertura',materia],queryFn:()=>getCoverage(materia)});const {data:materias=[]}=useMaterias();
 const list=(q.data||[]).filter(t=>filter==='TODOS'||(filter==='PENDÊNCIAS'?t.pendencias.length>0:t.estado===filter));
 return <AppLayout><div className="page-header"><h1 className="page-title">{review?'Lista de Revisão':'Conteúdos e cobertura'}</h1><p className="page-subtitle">Assuntos registrados, evidência recente e ações para a próxima sessão.</p></div><div className="flex flex-wrap gap-3 mb-6"><MateriaSelect value={materia} onChange={setMateria}/><select aria-label="Filtrar cobertura" className="form-select w-auto" value={filter} onChange={e=>setFilter(e.target.value)}>{['TODOS','PENDÊNCIAS','SEM REGISTRO','TEORIA SEM PRÁTICA','POUCA PRÁTICA','EVIDÊNCIA ANTIGA','PRÁTICA REGISTRADA'].map(s=><option key={s}>{s}</option>)}</select></div><p className="text-xs text-muted-foreground mb-5">Precisão dos últimos 60 dias, com tamanho da amostra. Contato recente não comprova memória; “sem registro” não significa que você nunca estudou fora do sistema. Os limites de 20 questões e 2 blocos são apenas orientações iniciais.</p>
 {q.isLoading?<LoadingState/>:q.isError?<ErrorState message={(q.error as Error).message}/>:!list.length?<EmptyState message="Nenhum assunto neste filtro. Escolha Todos para ver a cobertura."/>:<div className="grid lg:grid-cols-2 gap-4">{list.map(t=><TopicCard key={t.id} topic={t} materia={materias.find(m=>m.id===t.materia_id)?.nome||''}/>)}</div>}
 {!review&&<CatalogForm materia={materia}/>}
 </AppLayout>;
}
function TopicCard({topic:t,materia}:{topic:Coverage;materia:string}){
 const qc=useQueryClient();const [name,setName]=useState(t.nome);const [order,setOrder]=useState(t.ordem);const [ref,setRef]=useState(t.referencia||'');const [action,setAction]=useState('');const [date,setDate]=useState('');
 const save=useMutation({mutationFn:()=>studyPost(`assuntos/${t.id}`,{nome:name,ordem:order,referencia:ref||null},'PATCH'),onSuccess:()=>{qc.invalidateQueries();toast.success('Assunto atualizado.');},onError:(e:Error)=>toast.error(e.message)});
 const add=useMutation({mutationFn:()=>studyPost('acoes',{assunto_id:t.id,descricao:action,prevista_em:date?new Date(`${date}T12:00:00`).toISOString():null}),onSuccess:()=>{setAction('');qc.invalidateQueries();toast.success('Ação de revisão salva.');},onError:(e:Error)=>toast.error(e.message)});
 const resolve=useMutation({mutationFn:({id,result}:{id:string;result:string})=>studyPost(`acoes/${id}`,{resultado:result},'PATCH'),onSuccess:()=>qc.invalidateQueries(),onError:(e:Error)=>toast.error(e.message)});
 const base=`/estudar?materia=${t.materia_id}&assunto=${t.id}`;
 return <article className="tac-card space-y-3"><div className="flex justify-between gap-3"><div><p className="text-xs text-accent uppercase">{materia}</p><h2 className="text-base font-bold mt-1">{t.nome}</h2></div><span className="text-[10px] text-muted-foreground">Ordem {t.ordem}</span></div><span className="inline-block text-[10px] tracking-wider border border-accent/30 bg-accent/5 text-accent rounded-md px-2 py-1">{t.estado}</span><p className="text-xs text-muted-foreground">Último contato: {t.ultimo_contato?new Date(t.ultimo_contato).toLocaleDateString('pt-BR'):'sem registro'} · {t.total_questoes} questões no histórico</p><p className="text-sm">{t.precisao===null?'Sem precisão recente':`${t.precisao}% em ${t.questoes_recentes} questões / ${t.blocos_recentes} blocos recentes`}</p>{t.referencia&&<p className="text-xs text-muted-foreground">Material: {t.referencia}</p>}<Link className="text-sm text-accent underline inline-block" to={`${base}&atividade=${t.estado==='SEM REGISTRO'?'TEORIA':'QUESTOES'}`}>Estudar este assunto</Link>
 {t.pendencias.map(a=><div key={a.id} className="border border-warning/30 bg-warning/5 rounded-lg p-3 space-y-2"><p className="text-sm">{a.descricao}</p><p className="text-xs text-muted-foreground">Retomada: {new Date(a.prevista_em).toLocaleDateString('pt-BR')}{a.causa?` · causa relatada: ${a.causa}`:''}</p><div className="flex gap-3 flex-wrap text-xs"><Link className="text-accent underline" to={`${base}&atividade=${a.causa?'ANALISE_ERROS':'REVISAO'}&acao=${a.id}`}>Iniciar retomada</Link><button disabled={resolve.isPending} className="text-success underline" onClick={()=>resolve.mutate({id:a.id,result:'CONSEGUI'})}>Já realizei</button><button disabled={resolve.isPending} className="text-muted-foreground underline" onClick={()=>resolve.mutate({id:a.id,result:'REPETIR'})}>Reavaliar em 2 dias</button></div></div>)}
 <details><summary className="text-xs text-accent cursor-pointer">Programar revisão sem flashcards</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();add.mutate();}}><label className="text-xs block">O que fazer<input required maxLength={300} className="form-input mt-1" value={action} onChange={e=>setAction(e.target.value)} placeholder="Explicar sem consulta e resolver dois exemplos"/></label><label className="text-xs block">Data (opcional)<input type="date" className="form-input mt-1" value={date} onChange={e=>setDate(e.target.value)}/></label><button disabled={add.isPending} className="btn-tactical inline-flex items-center justify-center gap-2">Salvar revisão</button></form></details>
 <details><summary className="text-xs text-muted-foreground cursor-pointer">Ajustar nome, ordem ou material</summary><form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();save.mutate();}}><label className="block text-xs">Nome específico<input required maxLength={120} className="form-input mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><label className="block text-xs">Ordem dentro da matéria<input type="number" min="0" max="100000" className="form-input mt-1" value={order} onChange={e=>setOrder(Number(e.target.value))}/></label><label className="block text-xs">Material / capítulo / página<input maxLength={300} className="form-input mt-1" value={ref} onChange={e=>setRef(e.target.value)}/></label><button className="btn-tactical inline-flex items-center justify-center gap-2" disabled={save.isPending}>Salvar assunto</button></form></details>
 </article>;
}
function CatalogForm({materia}:{materia:string}){
 const qc=useQueryClient();const [name,setName]=useState('');const [newMateria,setNewMateria]=useState('');
 const add=useMutation({mutationFn:()=>request('/api/v1/performance/assuntos',{method:'POST',body:JSON.stringify({materia_id:materia,nome:name,semana_do_ciclo:1})}),onSuccess:()=>{setName('');qc.invalidateQueries();toast.success('Assunto cadastrado.');},onError:(e:Error)=>toast.error(e.message)});
 const addMateria=useMutation({mutationFn:()=>request('/api/v1/performance/materias',{method:'POST',body:JSON.stringify({nome:newMateria,peso_prova:1})}),onSuccess:()=>{setNewMateria('');qc.invalidateQueries();toast.success('Matéria cadastrada. Defina sua cota em Estudar agora.');},onError:(e:Error)=>toast.error(e.message)});
 return <details className="tac-card mt-6"><summary className="text-sm text-accent cursor-pointer">Cadastrar matéria ou próximo assunto</summary><div className="grid md:grid-cols-2 gap-5 mt-4"><form onSubmit={e=>{e.preventDefault();add.mutate();}} className="space-y-3"><label className="text-sm block">Novo assunto na matéria selecionada<input className="form-input mt-1" maxLength={120} required value={name} onChange={e=>setName(e.target.value)}/></label><button className="btn-tactical inline-flex items-center justify-center gap-2" disabled={!materia||add.isPending}>Adicionar assunto</button>{!materia&&<p className="text-xs text-muted-foreground">Selecione a matéria no filtro acima.</p>}</form><form onSubmit={e=>{e.preventDefault();addMateria.mutate();}} className="space-y-3"><label className="text-sm block">Nova matéria<input required maxLength={50} className="form-input mt-1" value={newMateria} onChange={e=>setNewMateria(e.target.value)}/></label><button className="btn-tactical inline-flex items-center justify-center gap-2" disabled={addMateria.isPending}>Adicionar matéria</button></form></div></details>;
}
