import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {toast} from 'sonner';
import {Link} from 'react-router-dom';
import AppLayout from '@/components/layout/AppLayout';
import {ErrorState,LoadingState} from '@/components/ui/states';
import {WeeklyGoals,StudySuggestions,GoalBar} from '@/components/dashboard/WeeklyGoals';
import {Profile,Week,getWeek,getProfile,goalsKey,duration} from '@/lib/goals';
import {request} from '@/lib/api';

export function Schedule({week:w}:{week:Week}) {
 return <section className="tac-card mb-6"><h2 className="font-bold mb-2">Cronograma e metas diárias</h2><p className="text-xs text-muted-foreground mb-4">Janelas não são horas líquidas. Pausas incluem alimentação e recuperação. Domingo: redação leve, sem horas presumidas.</p><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{w.dias.map(d=><div key={d.dia} className="border border-border rounded-lg p-3"><h3 className="text-accent font-semibold">{d.nome}</h3><p className="text-sm my-2">{d.inicio?`${d.inicio}–${d.fim}`:'Sem janela de horas'}</p><p className="text-xs text-muted-foreground mb-3">{d.inicio?`${d.pausas} min reservados para pausas`:'Redação e descanso'}</p><GoalBar label="Líquido" actual={d.realizado_minutos} target={d.meta_minutos} status={!d.meta_minutos?'SEM META':d.realizado_minutos>=d.meta_minutos?'META ATINGIDA':'REFERÊNCIA DO DIA'} format={duration}/></div>)}</div><p className="text-xs text-muted-foreground mt-4">Referência de horas esperada até agora: {duration(w.esperado_minutos)}. Capacidade restante nas janelas, após pausas: {duration(w.capacidade_restante_minutos)}. Os horários usam {w.fuso}.</p></section>;
}
function QuestionGoalEditor({week:w}:{week:Week}) {
 const [value,setValue]=useState(w.origem_questoes==='manual'?String(w.base_questoes):'175');
 const [future,setFuture]=useState(true);const qc=useQueryClient();
 const save=useMutation({mutationFn:(meta_questoes:number|null)=>request('/api/v1/metas/semana/questoes',{method:'PATCH',body:JSON.stringify({meta_questoes,proximas_semanas:future})}),onSuccess:()=>{qc.invalidateQueries();toast.success('Meta de questões salva. Seus registros foram preservados.');},onError:(e:Error)=>toast.error(e.message)});
 return <section className="tac-card mb-6"><h2 className="font-bold mb-2">Meta de questões — ajuste direto</h2><p className="text-sm text-muted-foreground mb-3">100 questões em 8h equivalem a 175 em 14h, se o ritmo e a mistura de atividades continuarem semelhantes. É uma referência inicial, não uma obrigação de acelerar ou deixar a correção de lado.</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();save.mutate(Number(value));}}><label className="block text-sm">Questões por semana (plano integral)<input aria-label="Meta semanal de questões" className="form-input mt-1 max-w-xs" type="number" min="1" max="5000" step="1" required value={value} onChange={e=>setValue(e.target.value)}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={future} onChange={e=>setFuture(e.target.checked)}/> Usar também nas próximas semanas</label><div className="flex flex-wrap gap-3"><button className="btn-tactical" disabled={save.isPending}>Salvar meta de questões</button><button className="text-accent text-sm underline" type="button" disabled={save.isPending} onClick={()=>save.mutate(null)}>Voltar ao cálculo automático</button></div><p className="text-xs text-muted-foreground">Atual: {w.meta_questoes} questões · {w.origem_questoes==='manual'?'Escolhida por você':'Cálculo automático'}. O ajuste de {w.percentual}% da semana também se aplica às questões. Para uma meta efetiva de 175, deixe o plano em 100%. Salvar não altera horas, redação nem ciclo.</p></form></section>;
}
function ProfileEditor({initial}:{initial:Profile}) {
 const [p,setP]=useState(()=>structuredClone(initial));const qc=useQueryClient();
 const save=useMutation({mutationFn:()=>request<{mensagem:string}>('/api/v1/metas/configuracao',{method:'PUT',body:JSON.stringify(p)}),onSuccess:r=>{toast.success(r.mensagem);qc.invalidateQueries({queryKey:goalsKey});},onError:(e:Error)=>toast.error(e.message)});
 const names=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
 return <form onSubmit={e=>{e.preventDefault();save.mutate();}} className="space-y-4 mt-4"><p className="text-sm text-muted-foreground">Alterações valem a partir da próxima semana. A meta atual fica estável; use o ajuste desta semana para reduzi-la.</p><div className="grid lg:grid-cols-2 gap-4">{p.dias.map((d,i)=><fieldset className="border border-border rounded-lg p-3" key={d.dia}><legend className="text-accent text-sm px-1">{names[d.dia]}</legend><div className="grid grid-cols-2 gap-3">{(['inicio','fim','pausas','minutos'] as const).map(k=><label className="text-xs" key={k}>{({inicio:'Início',fim:'Fim',pausas:'Pausas (min)',minutos:'Meta líquida (min)'})[k]}<input aria-label={`${names[d.dia]} ${k}`} className="form-input mt-1" type={k==='inicio'||k==='fim'?'time':'number'} min={k==='inicio'||k==='fim'?undefined:0} max={k==='inicio'||k==='fim'?undefined:600} step={k==='inicio'||k==='fim'?60:1} value={d[k]??''} onChange={e=>setP({...p,dias:p.dias.map((v,j)=>j===i?{...v,[k]:k==='inicio'||k==='fim'?e.target.value||null:Number(e.target.value)}:v)})}/></label>)}</div></fieldset>)}</div><div className="grid sm:grid-cols-3 gap-3"><label className="text-sm">Tempo para prática (%)<input className="form-input mt-1" type="number" min="10" max="70" value={p.percentual_pratica} onChange={e=>setP({...p,percentual_pratica:Number(e.target.value)})}/></label><label className="text-sm">Minutos por questão, sem histórico<input className="form-input mt-1" type="number" min="2" max="15" step="0.5" value={p.minutos_por_questao} onChange={e=>setP({...p,minutos_por_questao:Number(e.target.value)})}/></label><label className="text-sm">Redações semanais<input className="form-input mt-1" type="number" min="0" max="2" value={p.redacoes} onChange={e=>setP({...p,redacoes:Number(e.target.value)})}/></label></div><button className="btn-tactical" disabled={save.isPending}>{save.isPending?'Salvando...':'Salvar próximas semanas'}</button></form>;
}
export default function GoalsPage({scheduleOnly=false}:{scheduleOnly?:boolean}) {
 const q=useQuery({queryKey:[...goalsKey,'semana'],queryFn:getWeek});
 const profile=useQuery({queryKey:[...goalsKey,'configuracao'],queryFn:getProfile});const qc=useQueryClient();
 const adjust=useMutation({mutationFn:(percentual:number)=>request('/api/v1/metas/semana/ajuste',{method:'PATCH',body:JSON.stringify({percentual})}),onSuccess:()=>{qc.invalidateQueries();toast.success('Meta desta semana ajustada. Seus registros e o ciclo foram preservados.');},onError:(e:Error)=>toast.error(e.message)});
 return <AppLayout><div className="page-header"><h1 className="page-title">{scheduleOnly?'Cronograma Semanal':'Metas e orientação'}</h1><p className="page-subtitle">Um plano que cabe na sua semana, com margem para a vida real.</p></div>{q.isLoading?<LoadingState/>:q.isError?<ErrorState message="Falha ao carregar o planejamento."/>:q.data&&<>
 {!scheduleOnly&&<><WeeklyGoals/><QuestionGoalEditor key={`${q.data.inicio}-${q.data.base_questoes}-${q.data.origem_questoes}`} week={q.data}/></>}<Schedule week={q.data}/>
 {scheduleOnly?<Link className="btn-tactical inline-flex" to="/metas">Ajustar metas e cronograma</Link>:<>
 <section className="tac-card mb-6"><h2 className="font-bold mb-2">Ajuste desta semana</h2><p className="text-sm text-muted-foreground mb-3">Se faltou tempo, reduza a carga. Não acumulamos dívida para a próxima semana. A quantidade de redações permanece configurada; pausar zera todas as metas.</p><div className="flex flex-wrap gap-2">{[100,75,50,0].map(n=><button key={n} className={`btn-tactical ${q.data!.percentual===n?'ring-2 ring-accent':''}`} aria-pressed={q.data!.percentual===n} disabled={adjust.isPending} onClick={()=>adjust.mutate(n)}>{n?`${n}% do plano`:'Pausar semana'}</button>)}</div></section>
 <section className="tac-card mb-6"><h2 className="font-bold mb-2">Distribuição pelo ciclo</h2><p className="text-xs text-muted-foreground mb-4">A meta de horas é repartida proporcionalmente às cotas do ciclo no início da semana. É uma orientação; o ciclo real continua até completar, sem reiniciar na segunda-feira. Simulados globais contam no total, mas não são atribuídos a matérias.</p>{q.data.materias.length?<div className="grid sm:grid-cols-2 gap-4">{q.data.materias.map(m=><GoalBar key={m.materia_id} label={m.nome} actual={m.realizado_minutos} target={m.meta_minutos} format={duration} status={m.meta_minutos&&m.realizado_minutos>=m.meta_minutos?'META ATINGIDA':'COTA SEMANAL'}/>)}</div>:<Link className="text-accent underline" to="/estudar">Configure o ciclo para distribuir as horas</Link>}</section>
 <details className="tac-card mb-6"><summary className="font-bold cursor-pointer text-accent">Como a meta foi calculada</summary><p className="text-sm mt-3">Na configuração inicial, 21h05 de janelas dão origem a 14h líquidas, com pausas e margem. Isso é uma hipótese conservadora de planejamento, não uma quantidade cientificamente prescrita.</p>{q.data.origem_questoes==='manual'?<p className="text-sm mt-3">Meta escolhida por você: {q.data.base_questoes} questões no plano integral. Com o ajuste de {q.data.percentual}%, a meta atual é {q.data.meta_questoes}. O cálculo automático não substitui essa escolha.</p>:<><p className="text-sm mt-3">Questões: {q.data.percentual_pratica}% do tempo líquido para prática, divididos por {q.data.calibracao.minutos_por_questao} min por questão, arredondando para baixo em grupos de 5 antes do ajuste semanal. {q.data.calibracao.origem}</p><p className="text-xs text-muted-foreground mt-2">Amostra de calibração: {q.data.calibracao.blocos} blocos / {q.data.calibracao.questoes} questões. Calibra somente com pelo menos 3 blocos e 30 questões elegíveis dos 28 dias anteriores; não altera a meta no meio da semana. É uma estimativa global, não mede dificuldade ou domínio.</p></>}<p className="text-xs text-muted-foreground mt-2">Não escolha apenas questões fáceis para bater número; inclua a correção no tempo de estudo.</p></details>
 <details className="tac-card mb-6"><summary className="font-bold cursor-pointer text-accent">Configurar próximas semanas</summary>{profile.isLoading?<LoadingState/>:profile.isError?<ErrorState message="Falha ao carregar configuração."/>:profile.data&&<ProfileEditor initial={profile.data}/>}</details><StudySuggestions/>
 </>}
 </>}</AppLayout>;
}
